deploy:
  script:
    - pip3 install -U setuptools twine==2.0.0
    - python3 setup.py sdist
    - twine upload --skip-existing dist/tutor-figures*.tar.gz
  only:
    refs:
      - master
  tags:
    - private
